version: "3.1"
name: "greenlight"

services:
  db:
    image: postgres:16.1-alpine3.19
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
